### PR TITLE
Adding basic files 

### LINKED ISSUE #1: Bootstrapping the project (create-react-app)
Nothing much, just use create react app to get a general format ready.

### PR DESCRIPTION
**Pull request by AkMo3**
removed node_modules, uploaded all files in main file, used commit

### CODE REVIEW

**Comment by smit2k14** [comment]
This seems okay. Add a .gitignore file containing .vscode, and node_modules and you are good to go. Also, do not capitalise the commit names unless required (this is a personal thing, so no need to follow this for other projects).

Try something like this

`build: adding basic framework files`

Don't worry about it this time, I'll squash and merge so no issues there. Also, there was no need to close the earlier PR, you can still work there. Anyways, no issues, commit again and I'll merge. Cheers!

**Comment by AkMo3** [comment]
Done! Thanks a lot for your guidance. I have sent my proposal for SLoP, please have a look on that

**Comment by smit2k14** [comment]
Cool. A final tip, do not use same commit names. It becomes extremely difficult to navigate if the project size grows. Doesn't matter much for bootstrapping, but good going.

**Comment by AkMo3** [comment]
Sure I will keep that in mind

**Pull request merged**
